### ISSUE TITLE
remove or correct @internal tag usage

### ISSUE THREAD

**Issue by CybotTM** [ukko/phpredis-phpdoc#17]
at the moment IDE [PhpStorm] tells me i should not use `$redis->multi()`

according to phpdoc the internal tag is the opposite of the api tag - it should hide a function from external usage

using it to hide just documentation you need to use brackets around it

- https://github.com/ukko/phpredis-phpdoc/blob/master/src/Redis.php#L256
- http://phpdoc.org/docs/latest/references/phpdoc/tags/internal.html

thanks

**Comment by rickywiens** [comment]
I've made a pull request for this issue.

**Comment by CybotTM** [comment]
@rickywiens, thank you for providing the patch

**Comment by ukko** [comment]
@rickywiens and @CybotTM, thank you
