### ISSUE TITLE
incrByFloat doesn't work

### ISSUE THREAD

**Issue by roeim** [ukko/phpredis-phpdoc#19]
Hi,

I'm having trouble using $redis->incrByFloat on phpStorm.
It doesn't matter whether the key exists or not, the value is not incremented by the chosen amount.
Instead of using:
$redis->incrByFloat($key, $amount);
I am currently using:
$float = (float) $redis->get($key);
$redis->set($key, $float + $amount);
which works fine.

thanks

**Comment by ukko** [comment]
Hi

This repository with code autocompletion. Try to write to the author of the library https://github.com/phpredis/phpredis and/or to update/recompile your version of the library server and Redis. 

I hope that your problem will be solved.
