### ISSUE TITLE
Some methods are missing.. 

### ISSUE THREAD

**Issue by doodoori2** [ukko/phpredis-phpdoc#30]
I compare it with php_redis.h in phpredis. 
https://github.com/phpredis/phpredis/blob/ede43864a63db547319a01d14a8b272efd77de01/php_redis.h 

and found some methods are missing 
https://gist.github.com/doodoori2/55fb79a8251c091486a9e83979e5d712

**Comment by ukko** [comment]
Some methods added in #53
